apiVersion: wandelbots.com/v1alpha1
kind: App
metadata:
  name: rerun-logger
  namespace: cell
spec:
  appIcon: "app-icon.png"
  cellName: cell
  image: ghcr.io/wandelbotsgmbh/rerun-logger:1.1.2
  port: 8080
  healthPath: /
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
