apiVersion: wandelbots.com/v1alpha1
kind: App
metadata:
  name: rerun-viewer
  namespace: cell
spec:
  appIcon: "app-icon.png"
  cellName: cell
  image: wandelbots.azurecr.io/nova-apps/rerun-gateway:1.0.6
  port: 8080
  healthPath: /healthz
  environment:
    - name: RERUN_MEMORY_LIMIT
      value: "500MB"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2000Mi
