apiVersion: wandelbots.com/v1alpha1
kind: App
metadata:
  name: rerun-viewer
  namespace: cell
spec:
  appIcon: "logo_dark_mode.png"
  cellName: cell
  image: wandelbots.azurecr.io/rerun-gateway:0.1.0
  port: 8080
  healthPath: /healthz
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 1000Mi
